SELECT * FROM golfclub.course;
SELECT * FROM golfclub.course_fairway;

-- 取指定資料
SELECT seq, id, title, updateDate
FROM (
   SELECT CAST(@row_num := IF(@prev_value=Course.area,@row_num+1,1) AS UNSIGNED) AS seq,
		   Course.id AS id,
		   IF(Course.state = 1, concat('[＊]', Course.name), Course.name) AS title,
          Course.update_date AS updateDate,
			@prev_value := Course.area AS area
	  FROM golfclub.course Course,
		   (SELECT @row_num := 1) x,
		   (SELECT @prev_value := '') y
	 WHERE Course.area in (1,2,3,4)
	   AND Course.state like '%'
  ORDER BY Course.area, Course.state DESC, Course.order
	 ) subquery;

-- 取各地區球場分類數量
SELECT count(*) totalCount, area
  FROM golfclub.course
 WHERE area in (1,2,3,4)
   AND state like '%'
 GROUP BY area
 ORDER BY area;

-- 球場資料
-- info , traffic
SELECT Course.name AS `title`,
       Course.desc AS `desc`,
       Course.address AS `address`,
		Course.phone AS `phone`,
		Course.nScreen_name_img_seq AS `imageSeq`,
       Course.traffic_nScreen_img_seq AS `trafficSeq`
  FROM golfclub.course Course
 WHERE id = '211';

-- strategy
  SELECT * FROM golfclub.course_fairway;

  SELECT Fairway.zone AS `zone`,
         Fairway.hole_no AS `holeSeq`,
         Fairway.nScreen_img_seq AS `imageSeq`
    FROM golfclub.course_fairway Fairway
   WHERE Fairway.course_id = '10'
ORDER BY Fairway.zone, Fairway.hole_no;



-- 北台灣球場
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('1', '北台灣高爾夫球場(1)', '30', '31', '(02)2809-2466', '新北市淡水區八勢路301號', '(1)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '1', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('2', '北台灣高爾夫球場(2)', '32', '33', '(02)2809-2466', '新北市淡水區八勢路301號', '(2)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '2', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('3', '北台灣高爾夫球場(3)', '34', '35', '(02)2809-2466', '新北市淡水區八勢路301號', '(3)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '3', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('4', '北台灣高爾夫球場(4)', '36', '37', '(02)2809-2466', '新北市淡水區八勢路301號', '(4)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '4', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('5', '北台灣高爾夫球場(5)', '38', '39', '(02)2809-2466', '新北市淡水區八勢路301號', '(5)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '5', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('6', '北台灣高爾夫球場(6)', '40', '41', '(02)2809-2466', '新北市淡水區八勢路301號', '(6)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '6', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('7', '北台灣高爾夫球場(7)', '42', '43', '(02)2809-2466', '新北市淡水區八勢路301號', '(7)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '7', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('8', '北台灣高爾夫球場(8)', '44', '45', '(02)2809-2466', '新北市淡水區八勢路301號', '(8)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '8', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('9', '北台灣高爾夫球場(9)', '46', '47', '(02)2809-2466', '新北市淡水區八勢路301號', '(9)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '9', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('10', '北台灣高爾夫球場(10)', '48', '49', '(02)2809-2466', '新北市淡水區八勢路301號', '(10)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '10', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('11', '北台灣高爾夫球場(11)', '50', '51', '(02)2809-2466', '新北市淡水區八勢路301號', '(11)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '1', '11', '2', '2012-09-25 12:18:06', 'MingIn');

-- 桃竹苗球場
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('12', '桃竹苗高爾夫球場(12)', '30', '31', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(12)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '1', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('13', '桃竹苗高爾夫球場(13)', '32', '33', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(13)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '2', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('14', '桃竹苗高爾夫球場(14)', '34', '35', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(14)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '3', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('15', '桃竹苗高爾夫球場(15)', '36', '37', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(15)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '4', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('16', '桃竹苗高爾夫球場(16)', '38', '39', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(16)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '5', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('17', '桃竹苗高爾夫球場(17)', '40', '41', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(17)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '6', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('18', '桃竹苗高爾夫球場(18)', '42', '43', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(18)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '7', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('19', '桃竹苗高爾夫球場(19)', '44', '45', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(19)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '8', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('20', '桃竹苗高爾夫球場(20)', '46', '47', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(20)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '9', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('21', '桃竹苗高爾夫球場(21)', '48', '49', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(21)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '10', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('22', '桃竹苗高爾夫球場(22)', '50', '51', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(22)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '11', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('23', '桃竹苗高爾夫球場(23)', '52', '53', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(23)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '12', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('24', '桃竹苗高爾夫球場(24)', '54', '55', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(24)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '13', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('25', '桃竹苗高爾夫球場(25)', '56', '57', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(25)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '14', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('26', '桃竹苗高爾夫球場(26)', '58', '59', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(26)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '15', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('27', '桃竹苗高爾夫球場(27)', '60', '61', '(02)2809-2466', '桃竹苗淡水區八勢路301號', '(27)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '2', '16', '2', '2012-09-25 12:18:06', 'MingIn');

-- 中台灣球場
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('28', '中台灣高爾夫球場(28)', '30', '31', '(02)2809-2466', '中台灣淡水區八勢路301號', '(28)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '1', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('29', '中台灣高爾夫球場(29)', '32', '33', '(02)2809-2466', '中台灣淡水區八勢路301號', '(29)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '2', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('30', '中台灣高爾夫球場(30)', '34', '35', '(02)2809-2466', '中台灣淡水區八勢路301號', '(30)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '3', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('31', '中台灣高爾夫球場(31)', '36', '37', '(02)2809-2466', '中台灣淡水區八勢路301號', '(31)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '4', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('32', '中台灣高爾夫球場(32)', '38', '39', '(02)2809-2466', '中台灣淡水區八勢路301號', '(32)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '5', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('33', '中台灣高爾夫球場(33)', '40', '41', '(02)2809-2466', '中台灣淡水區八勢路301號', '(33)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '6', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('34', '中台灣高爾夫球場(34)', '42', '43', '(02)2809-2466', '中台灣淡水區八勢路301號', '(34)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '7', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('35', '中台灣高爾夫球場(35)', '44', '45', '(02)2809-2466', '中台灣淡水區八勢路301號', '(35)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '8', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('36', '中台灣高爾夫球場(36)', '46', '47', '(02)2809-2466', '中台灣淡水區八勢路301號', '(36)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '9', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('37', '中台灣高爾夫球場(37)', '48', '49', '(02)2809-2466', '中台灣淡水區八勢路301號', '(37)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '10', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('38', '中台灣高爾夫球場(38)', '50', '51', '(02)2809-2466', '中台灣淡水區八勢路301號', '(38)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '11', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('39', '中台灣高爾夫球場(39)', '52', '53', '(02)2809-2466', '中台灣淡水區八勢路301號', '(39)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '12', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('40', '中台灣高爾夫球場(40)', '54', '55', '(02)2809-2466', '中台灣淡水區八勢路301號', '(40)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '13', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('41', '中台灣高爾夫球場(41)', '56', '57', '(02)2809-2466', '中台灣淡水區八勢路301號', '(41)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '14', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('42', '中台灣高爾夫球場(42)', '58', '59', '(02)2809-2466', '中台灣淡水區八勢路301號', '(42)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '15', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('43', '中台灣高爾夫球場(43)', '60', '61', '(02)2809-2466', '中台灣淡水區八勢路301號', '(43)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '16', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('44', '中台灣高爾夫球場(44)', '62', '63', '(02)2809-2466', '中台灣淡水區八勢路301號', '(44)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '12', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('45', '中台灣高爾夫球場(45)', '64', '65', '(02)2809-2466', '中台灣淡水區八勢路301號', '(45)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '13', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('46', '中台灣高爾夫球場(46)', '66', '67', '(02)2809-2466', '中台灣淡水區八勢路301號', '(46)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '14', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('47', '中台灣高爾夫球場(47)', '68', '69', '(02)2809-2466', '中台灣水區八勢路301號號', '(47)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '15', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('48', '中台灣高爾夫球場(48)', '70', '71', '(02)2809-2466', '中台灣淡水區八勢路301號', '(48)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '3', '16', '2', '2012-09-25 12:18:06', 'MingIn');

-- 南台灣球場
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('49', '南台灣高爾夫球場(49)', '70', '71', '(02)2809-2466', '南台灣淡水區八勢路301號', '(49)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '4', '1', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('50', '南台灣高爾夫球場(50)', '72', '73', '(02)2809-2466', '南台灣淡水區八勢路301號', '(50)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '4', '2', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('51', '南台灣高爾夫球場(51)', '74', '75', '(02)2809-2466', '南台灣淡水區八勢路301號', '(51)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '4', '3', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('52', '南台灣高爾夫球場(52)', '76', '77', '(02)2809-2466', '南台灣淡水區八勢路301號', '(52)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '4', '4', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('53', '南台灣高爾夫球場(53)', '78', '79', '(02)2809-2466', '南台灣水區八勢路301號號', '(53)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '4', '5', '2', '2012-09-25 12:18:06', 'MingIn');
INSERT INTO `golfclub`.`course` (`id`, `name`, `sd_img_seq`, `hd_img_seq`, `phone`, `address`, `desc`, `desc1_sd_img_seq`, `desc1_hd_img_seq`, `desc2_sd_img_seq`, `desc2_hd_img_seq`, `traffic_sd_img_seq`, `traffic_hd_img_seq`, `area`, `order`, `state`, `update_date`, `login_username`) VALUES ('54', '南台灣高爾夫球場(54)', '80', '81', '(02)2809-2466', '南台灣淡水區八勢路301號', '(54)座落於大屯山西麓，由已故的中日兩位高壇耆老陳金獅與赤星四郎共同規劃設計，海拔150公尺，鄰近淡水河畔且與對岸的觀音山遙遙相望，山、河、海景一攬無遺。這座山地球場，堪稱是台灣地勢起伏最劇烈的球場之一。儘管球道並不長，但難度可不低；隨著山坡地形跌宕蜿蜒的球道，狹窄、高低落差甚大，且狗腿彎與盲眼洞甚多，再加上兩側濃密高聳的樹林與經常出現的OB樁，徹底考驗球員的距離與方向掌控、擊球策略與穩定性。\r「高球同學會」會員擊球優惠：\r平日2150元／假日2550元', '32', '33', '34', '35', '36', '37', '4', '6', '2', '2012-09-25 12:18:06', 'MingIn');
